### PR TITLE
Update testdata to model version 7000070

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/32)

### CODE REVIEW

**Comment by megahirt** [comment]
I was wondering why the test project has changed so much in addition to bumping the model version up to 70?  I'm sure there's a good reason.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/32#-:-KaoZeC8jIEjTWxPTgkZ:brulaud)*

**Comment by megahirt** [comment]
Reviewed 113 of 113 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/32)*

**Comment by megahirt** [comment]
:lgtm: as much as I can see.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/32#-:-Kao_K9FgmjPcUlhuEvt:bn44anw)*

**Comment by rmunn** [comment]
:lgtm: as well. This didn't get rid of *every* unit test failure, but after merging this locally I have only three failing tests remaining. That's good enough to merge this now and figure out the three failing tests later on.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/32#-:-Kau7m3NvC1R9A371O26:b-bqe19v)*

**Pull request merged**
