### PR TITLE
Use flexbridge for send/receive (v3)

### PR DESCRIPTION
**Pull request by ermshiperete**
This PR depends on [flexbridge PR #92](https://github.com/sillsdev/flexbridge/pull/92) and supersedes #13.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/15)

### CODE REVIEW

**Comment by regnrand** [comment]
1. Nothing in the LFMerge repo or any of its tests can reference, or use, anything in any FB assembly, except indirectly via LFBridge. Any prior changes that made internal classes/methods public and/or not sealed, must be reverted.

2. LfMerge should not reference or use anything an any Chorus assembly. That is the point of using FB.

3. You will be better off if you can figure out how to live without Autofac, especially, since it is newer than the one Chorus uses and both of them appear to want to be in the same "assembly soup" folder.

Doing #1 & #2 will then have your unit test effort focus on LfMerge behaviors, and not the behaviors of other code, such as Chorus or FB.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/LfMerge/LfMerge.csproj, line 42 \[r1\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/15#-KFtvfntYaRQ9jOlMLh0:-KFtvfntYaRQ9jOlMLh1:-1502706592) ([raw file](https://github.com/sillsdev/lfmerge/blob/af2d00535a9e40323bc6c496fea5d157f609e6b4/src/LfMerge/LfMerge.csproj#L42)):*
Will Autofac 3.5.2 cause problems with the version in Chorus (2.6.3.862)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/15#-:-KGJ0v95l9ghCCxaCghz:-296218358)*

**Comment by ermshiperete** [comment]
I agree that it would be better to move the clone action into FB. That would take care of the first two bullets and get rid of direct dependencies on Chorus (I think) and other FB assemblies. But that should be a separate task and not be included in this PR.

Regarding 3, so far we didn't have problems with Autofac versions. I also send an email to get some clarification why you prefer MEF over Autofac.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/LfMerge/LfMerge.csproj, line 42 \[r1\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/15#-KFtvfntYaRQ9jOlMLh0:-KGMlNtGdBH2njmxHlwz:-671460759) ([raw file](https://github.com/sillsdev/lfmerge/blob/af2d00535a9e40323bc6c496fea5d157f609e6b4/src/LfMerge/LfMerge.csproj#L42)):*
So far we didn't run into problems.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/15#-:-KGMjPfTaGT6KT0KZ-HP:-1255501660)*

**Comment by regnrand** [comment]
Could I do at least #1 in a prerequisite PR? LfMerge may, or may not, need to use Chorus directly in its handling of chorus notes.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/15#-:-KGNHjnujb3DEpPkmVff:2031441941)*

**Comment by ermshiperete** [comment]
Sure.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/15#-:-KGNWmjEVpfsSrxHpQnJ:-485110604)*

**Comment by regnrand** [comment]
Thanks. I'll get to it today.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/15#-:-KGNgeM9kMFx0E8jBwR-:-1808321207)*

**Pull request merged**
