### PR TITLE
Dequeue projects before running LfMerge

### PR DESCRIPTION
**Pull request by rmunn**
This should ensure that LF doesn't get "stuck" thinking the project is pending. Now, what can happen is that LF's pending message disappears a second or so before the project starts the S/R process, but that's not a bad experience from the user's point of view.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/39)

### CODE REVIEW

**Comment by megahirt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/LfMergeQueueManager/QueueManager.cs, line 56 at r1](https://reviewable.io:443/reviews/sillsdev/lfmerge/39#-KfQE65rBP5hB64aH9xF:-KfQE65rBP5hB64aH9xG:b9lfwt8) ([raw file](https://github.com/sillsdev/lfmerge/blob/c243cba80a2459345b5927ae180f88ec7dde5252/src/LfMergeQueueManager/QueueManager.cs#L56)):*
> ```Smalltalk
> 							modelVersion, true);
> 
> 						// TODO: If LfMerge fails, should we re-queue the project, or not?
> ```

no, we should not requeue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/39)*

**Comment by ermshiperete** [comment]
I don't see much difference compared to #30 (except that we return an error code that we don't use), but that doesn't matter. :lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/39#-:-KfuAocnpms68IPV5F9Q:b-jc6cat)*

**Comment by megahirt** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/39#-:-KfyWSh1f6yXXFpDBuFz:bnfp4nl)*

**Comment by rmunn** [comment]
There's no real benefit to this one over #30, except that having the error code gives us some future flexibility (for example, if we ever decide that we *do* want to requeue projects under certain conditions). If I had realized ahead of time that this PR would essentially end up the same as #30, I would have just merged #30 instead.

**Pull request merged**
