### PR TITLE
Adjust to current flexbridge

### PR DESCRIPTION
**Pull request by ermshiperete**
This change depends on [flexbridge PR #101](https://reviewable.io/reviews/sillsdev/flexbridge/101).

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/24)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org:45192/job/GitHub-LfMerge-Linux-any-master-release/92/

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org:45192/job/GitHub-LfMerge-Linux-any-master-release/93/

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org:45192/job/GitHub-LfMerge-Linux-any-master-release/94/

**Comment by rmunn** [comment]
Reviewed 7 of 16 files at r1, 8 of 11 files at r2, 1 of 3 files at r3, 1 of 4 files at r4, 15 of 15 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[build/LfMerge.proj, line 118 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJiuoxJOefL7TLD3zCD:-KJiuoxKQpm7lIVTCJR8:-1645602838) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/build/LfMerge.proj#L118)):*
> ```
> 			<ExistingFiles Include="$(RootDir)/output/$(Configuration)/*" Condition="'$(OS)'=='Unix'" />
> 			<FdoFiles Include="/usr/lib/lfmerge/*" Condition="'$(OS)'=='Unix'"
> 				Exclude="@(ExistingFiles -> '/usr/lib/lfmerge/%(FileName)%(Extension)')" />
> ```

BTW, where can I read more about that `@(... -> ...)` syntax? I hadn't seen it before. Actually, I'm pretty uninformed about .csproj syntax in general, and what's possible with it: for example, I don't know if `FdoFiles` is a special target, or the name of a group. I assume it's the latter, but I don't know.

---

*[src/LfMerge/LanguageForgeProject.cs, line 77 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJivUSBWozQU8ZOsOKX:-KJivUSCTQ0QtxssHeJX:-846349044) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/src/LfMerge/LanguageForgeProject.cs#L77)):*
> ```Smalltalk
> 			get
> 			{
> 				return Path.Combine(ProjectDir, string.Format("{0}{1}", ProjectCode,
> ```

FYI: There was some discussion with Ira, which I don't think got onto the Flowdock discussion so you might not have seen it. But we decided that we might want the project directory to match the project code that LanguageDepot knows about, but the filename to match the project code that LF knows about. That way there's a record on the filesystem of the mapping between the two names. I don't know if that could cause problems on the LfMergeBridge / FLEx / FDO end of things, and that's not an important feature right now. So this is not an impediment to accepting this PR, but something we'll want to think about for later.

---

*[src/LfMerge/LanguageForgeProject.cs, line 88 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJiwx4LL7VdJa-zzHBe:-KJiwx4M80VEPY-_Rmrh:-1504763444) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/src/LfMerge/LanguageForgeProject.cs#L88)):*
> ```Smalltalk
> 			get
> 			{
> 				if (_fieldWorksProject == null || _fieldWorksProject.IsDisposed)
> ```

Good idea!

---

*[src/LfMerge.Tests/OptionsTests.cs, line 64 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJjOp8MAjpweswn_6Vj:-KJjOp8MAjpweswn_6Vk:2113481128) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/src/LfMerge.Tests/OptionsTests.cs#L64)):*
> ```Smalltalk
> 		}
> 
> 		[TestCase(ActionNames.None, ActionNames.EnsureClone)]
> ```

I don't see an entry for "What is the next action after EnsureClone runs?" test case. I believe it would be `[TestCase(ActionNames.EnsureClone, ActionNames.None)]`, correct? Or does it not need a `GetNextAction()` test because of its special status?

---

*[src/LfMerge.Tests/Actions/SynchronizeActionTests.cs, line 174 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJjS5tbCqXYp5AA9I_J:-KJjS5tcqSsG99F0SE2S:833492797) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/src/LfMerge.Tests/Actions/SynchronizeActionTests.cs#L174)):*
> ```Smalltalk
> 
> 			// Verify
> 			Assert.That(GetGlossFromFdo(_testEntryGuid, 2), Is.EqualTo(lfChangedGloss));
> ```

This is a very nice cleanup. Thank you!

---

*[src/LfMerge.Tests/Fdo/DataConverters/ConvertFdoToMongoCustomFieldTests.cs, line 73 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJjSLiUR-4CxwwAyTrx:-KJjSLiUR-4CxwwAyTry:-543321632) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/src/LfMerge.Tests/Fdo/DataConverters/ConvertFdoToMongoCustomFieldTests.cs#L73)):*
> ```Smalltalk
> 			Assert.That(entry, Is.Not.Null);
> 			Dictionary<string, LfConfigFieldBase> lfCustomFieldList = new Dictionary<string, LfConfigFieldBase>();
> 			ConvertFdoToMongoCustomField converter = new ConvertFdoToMongoCustomField(cache,
> ```

FYI, when doing `ClassWithLongName instance = new ClassWithLongName()`, it's acceptable to use `var instance = new ClassWithLongName()` instead. The class of that variable is visible right there in the same line, so nobody's going to wonder about it while reading the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/24)*

**Comment by ermshiperete** [comment]
Review status: 21 of 435 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/LfMerge.proj, line 118 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJiuoxJOefL7TLD3zCD:-KLLVaB5lJ9snS8Q_F1G:-1886179642) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/build/LfMerge.proj#L118)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> BTW, where can I read more about that `@(... -> ...)` syntax? I hadn't seen it before. Actually, I'm pretty uninformed about .csproj syntax in general, and what's possible with it: for example, I don't know if `FdoFiles` is a special target, or the name of a group. I assume it's the latter, but I don't know.
</details>
You should be able to find that information in MSDN, e.g. https://msdn.microsoft.com/en-us/library/ms171476.aspx.

---

*[src/LfMerge.Tests/OptionsTests.cs, line 64 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJjOp8MAjpweswn_6Vj:-KLLbNTEd0PF8Af8jxbo:-803699443) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/src/LfMerge.Tests/OptionsTests.cs#L64)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> I don't see an entry for "What is the next action after EnsureClone runs?" test case. I believe it would be `[TestCase(ActionNames.EnsureClone, ActionNames.None)]`, correct? Or does it not need a `GetNextAction()` test because of its special status?
</details>
Done.

The correct action is `TransferMongoToFdo`. See also new REVIEW comment in `Options.cs`.

---

*[src/LfMerge.Tests/Fdo/DataConverters/ConvertFdoToMongoCustomFieldTests.cs, line 73 \[r5\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/24#-KJjSLiUR-4CxwwAyTrx:-KLLbkYdiSGWmF3U9uxt:-658553986) ([raw file](https://github.com/sillsdev/lfmerge/blob/290da98f516c80a64ca863302f0018d5b4146023/src/LfMerge.Tests/Fdo/DataConverters/ConvertFdoToMongoCustomFieldTests.cs#L73)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary>
> FYI, when doing `ClassWithLongName instance = new ClassWithLongName()`, it's acceptable to use `var instance = new ClassWithLongName()` instead. The class of that variable is visible right there in the same line, so nobody's going to wonder about it while reading the code.
</details>
That's what I usually do. Don't know why I explictly put the classname here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/24)*

**Pull request merged**
