### PR TITLE
Remove dependencies on Chorus & Flex Bridge (take 2)

### PR DESCRIPTION
**Pull request by regnrand**
I didn't run the tests, but two test fixtures are 'Ignored'
for now, since they aren't really units. You all can try
to restore them, if you really want them.

SynchronizeAction should work.

The EnsureClone method probably ought to be converted to a new
subclass of 'Action.

I switched your impl of IProjectIdentifier to use the regular
xml data store system, not that shared xml data store.

FwProject had set 'DisableDataMigration' to 'true',
but I see no reason to do that, so I set it to 'false'.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/20)

### CODE REVIEW

**Comment by megahirt** [comment]
Randy,

Thanks for this PR.  I appreciate your work.  We need another day to process this and we'll get back with you soon.

Thanks,

Chris

**Comment by ermshiperete** [comment]
@regnrand Randy, can you please rebase your changes to the latest on master? Then Jenkins should be able to automatically build it.

**Comment by regnrand** [comment]
@ermshiperete I did this version of the PR off the master branch's "Fix building on Windows" commit. I don;t see a newer commit on GH. (Maybe I need more git-fu skills.)

<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> @regnrand Randy, can you please rebase your changes to the latest on master? Then Jenkins should be able to automatically build it.</details>


---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/20#-:-KH_6qwpx-6KgEDSS4E8:1948599324)*

**Comment by ermshiperete** [comment]
@regnrand You need to fetch from sillsdev/LfMerge. The way I do it is that I name my fork `myfork` (which can be achieved by running `git remote rename origin myfork`) and add a `origin` that points to sillsdev/LfMerge: `git remote add origin https://github.com/sillsdev/LfMerge.git`. Then I can run `git fetch origin` or `git pull origin master` to get the latest changes, and later then `git push myfork <branchname>` for creating/updating a PR.

<details><summary><i>Previously, regnrand (Randy Regnier) wrote…</i></summary>
> @ermshiperete I did this version of the PR off the master branch's "Fix building on Windows" commit. I don;t see a newer commit on GH. (Maybe I need more git-fu skills.)</details>


---

Reviewed 4 of 13 files at r1.
Review status: 4 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/LfMerge/FieldWorks/ProjectIdentifier.cs, line 55 \[r1\]](https://reviewable.io:443/reviews/sillsdev/lfmerge/20#-KHV4rjy1JTXpw8Zmski:-KHV4rjy1JTXpw8Zmskj:-1849916) ([raw file](https://github.com/sillsdev/lfmerge/blob/642bbce04b699ca6e84564c0cd76bee9378ab559/src/LfMerge/FieldWorks/ProjectIdentifier.cs#L55)):*
> ```Smalltalk
> 		public string PipeHandle
> 		{
> 			// REVIEW Eberhard(RandyR): is this to be implemented, or should it really be NotSupportedException?
> ```

Good point. `NotSupportedException` would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/20#-:-KH_A55DhJdpijUOVgtj:-1727620424)*

**Pull request closed without merging**
