### PR TITLE
Handle unrecognized properties from Mongo (LF-48)

### PR DESCRIPTION
**Pull request by ermshiperete**
Instead of crashing we read them in a dictionary and log a warning message.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/44)

### CODE REVIEW

**Comment by megahirt** [comment]
:lgtm: I assume the [BsonExtraElements] is where the actual magic is to read in these unknown elements...

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/44#-:-L4wrgB-dHhrzD1usfZl:b20xbs1)*

**Comment by rmunn** [comment]
LGTM. Minor coding style comment about using `String.Join` rather than reimplementing it ourselves, but that shouldn't hold up this feature.

---

Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/LfMerge.Core/LanguageForge/Model/LfFieldBase.cs, line 59 at r2](https://reviewable.io:443/reviews/sillsdev/lfmerge/44#-L5mBqhd1Bly0oPPnxwY:-L5mBqhd1Bly0oPPnxwZ:b-8b28kq) ([raw file](https://github.com/sillsdev/lfmerge/blob/25dbe1e45bf1fec16f8b931b246d2a2c288baf29/src/LfMerge.Core/LanguageForge/Model/LfFieldBase.cs#L59)):*
> ```Smalltalk
> 				ExtraElements.Count, GetType().Name);
> 			bool firstKey = true;
> 			foreach (var key in ExtraElements.Keys)
> ```

This `foreach` loop could be replaced with `bldr.Append(String.Join(", ", ExtraElements.Keys))`, which to my mind is a little easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/44#-:-L5mD-wQQsiz8kA1RQuK:b-vgxqm)*

**Comment by rmunn** [comment]
First Jenkins build failed because it pulled the wrong LibPalaso version. A later build succeeded, but the GitHub status message didn't get updated due to a 422 error. I'm going to try closing and re-opening this PR to make GitHub kick off a new Jenkins build, and hope that that's enough to get past the 422 so that GitHub will allow this PR to be merged.

**Comment by ermshiperete** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LfMerge.Core/LanguageForge/Model/LfFieldBase.cs, line 59 at r2](https://reviewable.io:443/reviews/sillsdev/lfmerge/44#-L5mBqhd1Bly0oPPnxwY:-L5mWYHOeEtr_-IYQZ0f:baq4ivg) ([raw file](https://github.com/sillsdev/lfmerge/blob/25dbe1e45bf1fec16f8b931b246d2a2c288baf29/src/LfMerge.Core/LanguageForge/Model/LfFieldBase.cs#L59)):*
<details><summary><i>Previously, rmunn (Robin Munn) wrote…</i></summary><blockquote>

This `foreach` loop could be replaced with `bldr.Append(String.Join(", ", ExtraElements.Keys))`, which to my mind is a little easier to read.
</blockquote></details>

Of course you're right. That's one of those convenient methods that I always forget unless R#/Rider reminds me - and for LfMerge I still have to use MonoDevelop, so I don't have the R# functionality there...

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/lfmerge/44)*

**Pull request merged**
