### PR TITLE
No more calling PHP code from LfMerge

### PR DESCRIPTION
**Pull request by rmunn**
This PR finally implements the updateCustomFieldViews logic in LfMerge, as part of the SetCustomFieldConfig method in MongoConnection (which is where the logic belongs anyway). This will allow us to move the `lfmerge` package into its own container in Language Forge, instead of having it so tightly coupled to the PHP container.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/173)

### CODE REVIEW

**Review by megahirt — COMMENTED** [review]
looks good so far!

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/173#-:-MqK_VyN1ncn9cSF-KUL:b-xo2sg4)* status: 0 of 1 LGTMs obtained (waiting on @rmunn)

**Comment by rmunn** [comment]
Just ran a test, and got Send/Receive to complete correctly, but the custom field ended up with a type of "basic" instead of "multitext". Should be pretty straightforward to figure out why, but this isn't quite ready to merge yet.

**Comment by rmunn** [comment]
Tested and working now, so now I can remove the bit from the Dockerfile that pulls in the web-languageforge image. That should make the lfmerge images much smaller and speed up the build time. Then it will be ready for review.

**Review by megahirt — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/lfmerge/173#-:-MqNz2I54IJAwy2Hejwv:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained (waiting on @rmunn)

**Pull request merged**
